#!/usr/bin/env node
/**
 * brine-theme preview builder.
 *
 * Regenerates the generated parts of preview/ from a real Pterodactyl checkout:
 *
 *   preview/icons.js                 inline SVG paths (FontAwesome free-solid)
 *   preview/panel-preview.css        Tailwind build of panel-preview.source.css
 *   preview/fonts/*.woff2            Montserrat + Playfair Display variable fonts
 *
 * Usage:
 *
 *   node preview/build-preview.js --panel /var/www/pterodactyl
 *
 * The panel directory only needs its node_modules installed (yarn install) and
 * its original public/themes tree - no database, no built assets.
 */

"use strict";

const fs = require("fs");
const path = require("path");

const PREVIEW_DIR = __dirname;
const THEME_DIR = path.resolve(PREVIEW_DIR, "..", "theme");

const ICONS = {
  sun: "faSun",
  moon: "faMoon",
  bars: "faBars",
  times: "faTimes",
  "layer-group": "faLayerGroup",
  server: "faServer",
  terminal: "faTerminal",
  folder: "faFolder",
  "folder-open": "faFolderOpen",
  database: "faDatabase",
  "calendar-alt": "faCalendarAlt",
  users: "faUsers",
  archive: "faArchive",
  "network-wired": "faNetworkWired",
  "sliders-h": "faSlidersH",
  cog: "faCog",
  cogs: "faCogs",
  history: "faHistory",
  key: "faKey",
  "sign-out-alt": "faSignOutAlt",
  search: "faSearch",
  "user-circle": "faUserCircle",
  play: "faPlay",
  stop: "faStop",
  redo: "faRedo",
  bolt: "faBolt",
  "power-off": "faPowerOff",
  upload: "faUpload",
  "file-alt": "faFileAlt",
  plus: "faPlus",
  sync: "faSync",
  "chevron-right": "faChevronRight",
  "chevron-left": "faChevronLeft",
  "chevron-down": "faChevronDown",
  "graduation-cap": "faGraduationCap",
  "book-open": "faBookOpen",
  home: "faHome",
  "list-ul": "faListUl",
  "ellipsis-v": "faEllipsisV",
  "check-circle": "faCheckCircle",
  "exclamation-circle": "faExclamationCircle",
  "exclamation-triangle": "faExclamationTriangle",
  "shield-alt": "faShieldAlt",
  hdd: "faHdd",
  memory: "faMemory",
  cpu: "faMicrochip",
  clock: "faClock",
  wifi: "faWifi",
  "trash-alt": "faTrashAlt",
};

function parseArgs(argv) {
  let panel = process.cwd();

  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--panel" && argv[i + 1]) {
      panel = argv[++i];
    } else if (argv[i] === "--help" || argv[i] === "-h") {
      console.log("Usage: node preview/build-preview.js --panel <panel-root>");
      process.exit(0);
    }
  }

  return path.resolve(panel);
}

function resolveFrom(panel, request) {
  const nodeModules = path.join(panel, "node_modules");
  if (!fs.existsSync(nodeModules)) {
    throw new Error(
      `no node_modules in ${panel} - run "yarn install" in the panel first`
    );
  }
  return require(require.resolve(request, { paths: [nodeModules] }));
}

async function step(label, fn) {
  try {
    const detail = await fn();
    console.log(`  ok    ${label}${detail ? ` (${detail})` : ""}`);
  } catch (error) {
    console.warn(`  SKIP  ${label}: ${error.message}`);
  }
}

async function requireStep(label, fn) {
  const detail = await fn();
  console.log(`  ok    ${label}${detail ? ` (${detail})` : ""}`);
}

function buildIcons(panel) {
  const fa = resolveFrom(panel, "@fortawesome/free-solid-svg-icons");
  const out = {};
  const missing = [];

  for (const [key, exportName] of Object.entries(ICONS)) {
    const icon = fa[exportName];
    if (!icon || !Array.isArray(icon.icon)) {
      missing.push(exportName);
      continue;
    }

    const [width, height, , , svgPathData] = icon.icon;
    out[key] = [`0 0 ${width} ${height}`, svgPathData];
  }

  if (Object.keys(out).length === 0) {
    throw new Error("no usable icons found");
  }
  if (missing.length) {
    console.warn(`         missing icons: ${missing.join(", ")}`);
  }

  const file = path.join(PREVIEW_DIR, "icons.js");
  fs.writeFileSync(
    file,
    `/* Generated by preview/build-preview.js - do not edit. */\nvar PTERO_ICONS = ${JSON.stringify(
      out,
      null,
      0
    )};\n`
  );

  return `${Object.keys(out).length} icons -> ${path.basename(file)}`;
}

async function buildCss(panel) {
  const postcss = resolveFrom(panel, "postcss");
  const tailwindcss = resolveFrom(panel, "tailwindcss");

  const content = ["index.html"]
    .map((name) => path.join(PREVIEW_DIR, name))
    .filter((file) => fs.existsSync(file));

  if (content.length === 0) {
    throw new Error("no preview html found");
  }

  // The theme config sits outside the panel, so its own requires
  // (tailwindcss/colors, @tailwindcss/forms) would not resolve from there.
  // Copy it into the panel root so every bare require finds the panel's
  // node_modules, then wrap it to point content at the preview markup.
  const baseName = ".__ptero_preview.base.config.js";
  const wrapperName = ".__ptero_preview.config.js";
  const baseFile = path.join(panel, baseName);
  const wrapperFile = path.join(panel, wrapperName);

  fs.copyFileSync(path.join(THEME_DIR, "tailwind.config.js"), baseFile);
  fs.writeFileSync(
    wrapperFile,
    [
      `'use strict';`,
      `const base = require('./${baseName}');`,
      `module.exports = Object.assign({}, base, { content: ${JSON.stringify(
        content
      )} });`,
      "",
    ].join("\n")
  );

  try {
    const input = path.join(PREVIEW_DIR, "panel-preview.source.css");
    const output = path.join(PREVIEW_DIR, "panel-preview.css");

    const result = await postcss([
      tailwindcss({ config: wrapperFile }),
    ]).process(fs.readFileSync(input, "utf8"), {
      from: input,
      to: output,
    });

    fs.writeFileSync(output, result.css);
    return `${content.length} html, ${(result.css.length / 1024).toFixed(
      1
    )} KB`;
  } finally {
    fs.rmSync(baseFile, { force: true });
    fs.rmSync(wrapperFile, { force: true });
  }
}

async function main() {
  const panel = parseArgs(process.argv.slice(2));

  if (!fs.existsSync(path.join(panel, "package.json"))) {
    throw new Error(
      `'${panel}' does not look like a panel root (no package.json)`
    );
  }

  console.log(`brine-theme preview build`);
  console.log(`  panel: ${panel}`);
  console.log("");

  await requireStep("icons", () => buildIcons(panel));
  await requireStep("tailwind", () => buildCss(panel));

  console.log("");
  console.log(
    "Open preview/index.html to see the themed user panel."
  );
}

main().catch((error) => {
  console.error(`\nerror: ${error.message}`);
  process.exit(1);
});
